# Generated by Django 3.0.2 on 2020-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=255, verbose_name='単語')),
                ('meanings', models.CharField(max_length=255, verbose_name='意味')),
                ('part_of_speech', models.CharField(max_length=255, verbose_name='品詞')),
                ('synonym', models.CharField(max_length=255, verbose_name='類義語')),
                ('sentence', models.CharField(max_length=255, verbose_name='例文')),
            ],
        ),
    ]
